# ============================================================
# CRITICAL: logfire MUST be configured before ALL other imports
# so that spans from all modules are captured from the start.
# ============================================================
import logfire
import os
from dotenv import load_dotenv
from contextlib import asynccontextmanager

load_dotenv()
logfire.configure(token=os.getenv("LOGFIRE_TOKEN"))

# Now safe to import app modules - logfire is already active
from fastapi import FastAPI, Response, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.concurrency import run_in_threadpool
from pydantic import BaseModel, Field
from typing import List
from psycopg_pool import AsyncConnectionPool
from psycopg.rows import dict_row
from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver

from app.agents.graph import workflow
from app.guardrails.rails import initialize_rails, guard
from app.config import settings

# Global variable to hold the compiled agent
rag_agent = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Handles startup (DB connections, guardrails) and shutdown.
    """
    global rag_agent
    
    # Initialize guardrails
    initialize_rails()
    
    # Initialize Async Database Pool for LangGraph Memory
    # max_size=20 allows 20 concurrent customer queries to run simultaneously
    SUPABASE_URI = settings.SUPABASE_URI
    async with AsyncConnectionPool(
        conninfo=SUPABASE_URI, 
        max_size=20,
        kwargs={
            "autocommit": True, 
            "prepare_threshold": None,
            "row_factory": dict_row  # <--- Essential for LangGraph
        }
    ) as pool:
        
        app.state.pool = pool
        
        checkpointer = AsyncPostgresSaver(pool)
        
        # Automatically create Supabase tables if they don't exist
        await checkpointer.setup()
        
        # Compile the graph with the async checkpointer
        rag_agent = workflow.compile(checkpointer=checkpointer)
        
        # The app serves traffic while inside this block
        yield
        
    # The pool automatically closes when the server shuts down.

# Initialize FastAPI
app = FastAPI(
    title="Agentic RAG API",
    description="An Enterprise Chatbot",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://lumioafrica.com", "https://www.lumioafrica.com"],  # In production, replace ["*"] with your actual frontend URLs
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class QueryRequest(BaseModel):
    q: str = Field(..., description="The message sent by the user.")
    thread_id: str = Field(..., description="Unique identifier tracking this specific conversation session.")

class QueryResponse(BaseModel):
    question: str = Field(..., description="The original query sent by the user.")
    answer: str = Field(..., description="The final answer generated by the RAG agent.")
    thought_process: List[str] = Field(default=[], description="The step-by-step execution plan taken by the agent.")
    status: str = Field(..., description="The final execution state of the graph.")
    sources: List[dict] = Field(default=[], description="List of source documents used to ground the answer.")
    
@app.get("/")
def home():
    return {"message": "Enterprise LangGraph RAG API is live."}

@app.get("/health", status_code=200)
async def health_check(request: Request):
    """
    Checks active database connectivity AND verifies the AI agent is loaded.
    """
    # 1. Check if the LangGraph agent is compiled and ready in memory
    global rag_agent
    agent_ready = rag_agent is not None
    if not agent_ready:
        logfire.error("❌ Health check failed: LangGraph agent is not compiled or ready.")

    # 2. Check if the database connection pool is actively responding
    db_ready = False
    try:
        async with request.app.state.pool.connection() as conn:
            await conn.execute("SELECT 1")
        db_ready = True
    except Exception as e:
        logfire.error(f"Database health check failed: {e}")

    # 3. If either component fails, report 503 Service Unavailable
    if not agent_ready or not db_ready:
        return Response(
            content=f"unhealthy (agent_ready={agent_ready}, db_ready={db_ready})", 
            media_type="text/plain", 
            status_code=503
        )

    # 4. If all systems are nominal
    return {
        "status": "healthy",
        "database": "connected",
        "agent": "compiled"
    }

@app.get("/graph")
def get_graph_image():
    """
    Returns the Mermaid image of the agent's workflow.
    """
    try:
        png_bytes = rag_agent.get_graph().draw_mermaid_png()
        return Response(content=png_bytes, media_type="image/png")
    except Exception as e:
        return {"error": f"Could not generate graph image: {e}"}
    
@app.post("/query", response_model=QueryResponse)
async def query(request: QueryRequest):
    """
    Executes the LangGraph RAG flow with memory using a POST request.
    """
    q = request.q
    thread_id = request.thread_id

    initial_state = {
        "messages": [{"role": "user", "content": q}],
        "current_query": q,
        "documents": [],
        "plan": ["Start"],
        "status": "Initializing Graph...",
        "final_answer": ""
    }
    
    # Configuration for Memory (Thread ID)
    config = {"configurable": {"thread_id": thread_id}}
    
    try:
        # Gate 1: NeMo Guardrails — blocks off-topic, jailbreaks, and handles dialog
        rail_fired, rail_response = await run_in_threadpool(guard, q)
        if rail_fired:
            logfire.info(f"🛡️ Request blocked by guardrails | thread={thread_id}")
            return {
                "question": q,
                "answer": rail_response,
                "thought_process": ["Intent: Guardrails Fired", "Retrieval: Skipped"],
                "status": "Blocked by guardrails.",
                "sources": []
            }

        # Gate 2: LangGraph RAG pipeline
        # Run the graph asynchronously to preserve Logfire context variables
        final_output = await rag_agent.ainvoke(initial_state, config=config)
        
        return {
            "question": q,
            "answer": final_output.get("final_answer"),
            "thought_process": final_output.get("plan"),
            "status": final_output.get("status"),
            "sources": final_output.get("documents", [])
        }
    except Exception as e:
        logfire.error(f"❌ Backend Execution Failed: {e}")
        return {
            "question": q,
            "answer": "I apologize, but I encountered an internal error while processing your request. Please try again later.",
            "thought_process": ["Error encountered during execution."],
            "status": "error",
            "sources": []
        }